//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   金融関係|ショッピング|公共インフラ|その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート完了！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contents_Information_Export {
            get {
                return ResourceManager.GetString("Contents_Information_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート完了! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contents_Information_Import {
            get {
                return ResourceManager.GetString("Contents_Information_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除してよいですか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contents_Question_Delete {
            get {
                return ResourceManager.GetString("Contents_Question_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード欄が空です。このまま登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contents_Question_NothingPassword {
            get {
                return ResourceManager.GetString("Contents_Question_NothingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に同名のデータが存在しています。上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contents_Question_Overwrite {
            get {
                return ResourceManager.GetString("Contents_Question_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイル(*.csv)|*.csv|テキストファイル(*.txt)|*.txt|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Csv_Filter {
            get {
                return ResourceManager.GetString("Csv_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このファイルはインポートできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Cannot_Import {
            get {
                return ResourceManager.GetString("Error_Cannot_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目の値が不正です。(項目数：{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Invalid_Value {
            get {
                return ResourceManager.GetString("Error_Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasswordChar {
            get {
                return ResourceManager.GetString("PasswordChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートしたいファイルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Export {
            get {
                return ResourceManager.GetString("Title_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートしたいファイルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Import {
            get {
                return ResourceManager.GetString("Title_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title_Question {
            get {
                return ResourceManager.GetString("Title_Question", resourceCulture);
            }
        }
    }
}
